# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f2c5dd73e187c8f65c95cb0bc76ee9251ba4adb911499728982237b237bb28c1fc64b7f2438bbcb8d455f3c3628afa4612cedbc9654aac77a2e5984b864812

test:
  secret_key_base: cc253969dfaa95fc778f17cb1a533e0d199578424e3f92c40c5f6066bef0516f90f2cb4cecbd1da3546f2c41a38bf88eb2d35b554666a2604aeef9216f27ea12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
